api_platform:
    title: 'Test UBI Mhemed Ben AOUN API'
    description: 'A Symfony API to response the test UBI.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
        html:
            mime_types: [ 'text/html' ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
