version: '3'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: rootPwd
            MYSQL_DATABASE: testubi
            MYSQL_USER: testUbiUsr
            MYSQL_PASSWORD: testUbiMdp
    redis:
        image: 'bitnami/redis:latest'
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        links:
            - db:mysqldb
            - redis
        volumes:
            - .:/var/www/
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        links:
            - php
        volumes:
            - .:/var/www/
        ports:
            - 80:80